---
- name: Installing gpg key
  become: '{{ vagrant_escalate }}'
  become_user: root
  ansible.builtin.apt_key:
    url: '{{ vagrant_apt_key }}'
    state: present
- name: Installing {{ vagrant_tmp_pkg }}
  become: '{{ vagrant_escalate }}'
  become_user: root
  ansible.builtin.apt:
    deb: '{{ vagrant_tmp_pkg }}'
    state: present
