---
- name: Attaching {{ vagrant_pkg_fq }}
  become: true
  become_user: root
  ansible.builtin.command: hdiutil attach {{ vagrant_pkg_fq }}
  args:
    creates: '{{ vagrant_dmg_volume }}'

- name: Installing pkg {{ vagrant_dmg_pkg_path }}
  become: true
  become_user: root
  ansible.builtin.command: installer -pkg {{ vagrant_dmg_pkg_path | to_json }} -target
  changed_when: false
