---
- name: Adding rpm key {{ vagrant_rpm_key }}
  become: '{{ vagrant_escalate }}'
  become_user: root
  ansible.builtin.rpm_key:
    key: '{{ vagrant_rpm_key }}'
    state: present
- name: Installing {{ vagrant_tmp_pkg }}
  become: '{{ vagrant_escalate }}'
  become_user: root
  ansible.builtin.yum:
    name: '{{ vagrant_tmp_pkg }}'
