---
- name: adding rpm key
  become: '{{ vagrant_escalate }}'
  become_user: root
  rpm_key:
    key: '{{ vagrant_rpm_key }}'
    state: present
- name: installing {{ vagrant_tmp_pkg }}
  become: '{{ vagrant_escalate }}'
  become_user: root
  package:
    name: '{{ vagrant_tmp_pkg }}'
    state: present
